import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import nodemailer from 'nodemailer';

interface Conversation {
  id: string;
  session_id: string;
  question: string;
  answer: string;
  created_at: string;
}

// Generate HTML report for a given date
function generateHTMLReport(conversations: Conversation[], dateStr: string): string {
  const grouped: Record<string, Conversation[]> = {};
  conversations.forEach((c) => {
    if (!grouped[c.session_id]) grouped[c.session_id] = [];
    grouped[c.session_id].push(c);
  });

  const sessionBlocks = Object.entries(grouped).map(([sessionId, convos], idx) => {
    const rows = convos.map((c) => `
      <tr>
        <td style="padding:10px 14px;border-bottom:1px solid #eee;color:#333;vertical-align:top;width:35%;">${escapeHtml(c.question)}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #eee;color:#555;vertical-align:top;">${escapeHtml(c.answer)}</td>
        <td style="padding:10px 14px;border-bottom:1px solid #eee;color:#888;white-space:nowrap;vertical-align:top;">${new Date(c.created_at).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</td>
      </tr>
    `).join('');

    return `
      <div style="margin-bottom:28px;">
        <h3 style="color:#4f46e5;font-size:14px;margin-bottom:8px;font-weight:600;">Session ${idx + 1} <span style="color:#aaa;font-weight:400;font-size:12px;">(${sessionId.slice(0, 20)}...)</span></h3>
        <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;">
          <thead>
            <tr style="background:#f8f9ff;">
              <th style="padding:10px 14px;text-align:left;font-size:12px;color:#6b7280;font-weight:600;text-transform:uppercase;">Question</th>
              <th style="padding:10px 14px;text-align:left;font-size:12px;color:#6b7280;font-weight:600;text-transform:uppercase;">AI Answer</th>
              <th style="padding:10px 14px;text-align:left;font-size:12px;color:#6b7280;font-weight:600;text-transform:uppercase;">Time</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>
    `;
  }).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>HanXcel AI - Chatbot Report - ${dateStr}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background: #f4f5f7; color: #333; }
        .container { max-width: 800px; margin: 0 auto; padding: 32px 24px; }
        .header { background: linear-gradient(135deg, #4f46e5, #7c3aed); color: white; padding: 32px; border-radius: 12px 12px 0 0; text-align: center; }
        .header h1 { margin: 0 0 4px 0; font-size: 22px; }
        .header p { margin: 0; opacity: 0.9; font-size: 14px; }
        .body { background: white; padding: 28px; border-radius: 0 0 12px 12px; }
        .summary { display: flex; gap: 16px; margin-bottom: 28px; }
        .summary-card { flex: 1; background: #f8f9ff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; text-align: center; }
        .summary-card .num { font-size: 28px; font-weight: 700; color: #4f46e5; }
        .summary-card .label { font-size: 12px; color: #6b7280; margin-top: 4px; }
        .footer { text-align: center; padding: 20px; color: #9ca3af; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>🤖 Chatbot Daily Report</h1>
          <p>${dateStr} • HanXcel AI Technologies</p>
        </div>
        <div class="body">
          <div class="summary">
            <div class="summary-card">
              <div class="num">${conversations.length}</div>
              <div class="label">Total Q&A</div>
            </div>
            <div class="summary-card">
              <div class="num">${Object.keys(grouped).length}</div>
              <div class="label">Sessions</div>
            </div>
          </div>
          ${conversations.length > 0 ? sessionBlocks : '<p style="text-align:center;color:#9ca3af;padding:40px 0;">No chatbot conversations recorded for this date.</p>'}
        </div>
        <div class="footer">
          Auto-generated by HanXcel AI Admin System • ${new Date().toISOString()}
        </div>
      </div>
    </body>
    </html>
  `;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/\n/g, '<br>');
}

// Helper to clean JSON-stored string values from Supabase
function cleanValue(val: unknown): string {
  if (typeof val === 'string') return val.replace(/^"|"$/g, '');
  return String(val || '');
}

// GET: Download report as HTML document
export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const dateParam = searchParams.get('date') || new Date().toISOString().split('T')[0];

    const startOfDay = `${dateParam}T00:00:00.000Z`;
    const endOfDay = `${dateParam}T23:59:59.999Z`;

    const { data: conversations } = await supabase
      .from('chatbot_conversations')
      .select('*')
      .gte('created_at', startOfDay)
      .lte('created_at', endOfDay)
      .order('created_at', { ascending: true });

    const html = generateHTMLReport(conversations || [], dateParam);

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="chatbot-report-${dateParam}.html"`,
      },
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

// POST: Send email report via Gmail SMTP (Nodemailer)
export async function POST(req: Request) {
  try {
    const body = await req.json().catch(() => ({}));
    const dateParam = body.date || new Date().toISOString().split('T')[0];

    // Fetch all email-related settings from admin
    const { data: settingsData } = await supabase
      .from('site_settings')
      .select('key, value')
      .in('key', ['chatbot_report_email', 'smtp_email', 'smtp_password']);

    const settings: Record<string, string> = {};
    settingsData?.forEach((row) => {
      settings[row.key] = cleanValue(row.value);
    });

    const recipientEmail = body.email || settings.chatbot_report_email;
    const smtpEmail = settings.smtp_email;
    const smtpPassword = settings.smtp_password ? settings.smtp_password.replace(/\s+/g, '') : '';

    if (!recipientEmail) {
      return NextResponse.json({ 
        error: 'No recipient email configured. Set it in Admin → Chatbot & Logs → Report Settings.' 
      }, { status: 400 });
    }

    if (!smtpEmail || !smtpPassword) {
      return NextResponse.json({ 
        error: 'SMTP email credentials not configured. Go to Admin → Chatbot & Logs → Report Settings and enter your Gmail address and App Password.' 
      }, { status: 400 });
    }

    // Fetch conversations for the date
    const startOfDay = `${dateParam}T00:00:00.000Z`;
    const endOfDay = `${dateParam}T23:59:59.999Z`;

    const { data: conversations } = await supabase
      .from('chatbot_conversations')
      .select('*')
      .gte('created_at', startOfDay)
      .lte('created_at', endOfDay)
      .order('created_at', { ascending: true });

    const html = generateHTMLReport(conversations || [], dateParam);

    // Create Nodemailer transporter with Gmail SMTP
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: smtpEmail,
        pass: smtpPassword,
      },
    });

    // Send the email
    const info = await transporter.sendMail({
      from: `"HanXcel AI Reports" <${smtpEmail}>`,
      to: recipientEmail,
      subject: `🤖 Chatbot Daily Report - ${dateParam}`,
      html: html,
    });

    return NextResponse.json({ 
      success: true, 
      message: `Report sent to ${recipientEmail}`,
      messageId: info.messageId,
      totalConversations: (conversations || []).length,
    });
  } catch (error: any) {
    console.error('Email send error:', error);
    
    // Provide user-friendly error messages
    let errorMessage = error.message || 'Failed to send email';
    if (error.code === 'EAUTH') {
      errorMessage = 'Gmail authentication failed. Make sure you are using a valid Gmail App Password (not your regular password). Go to myaccount.google.com → Security → 2-Step Verification → App Passwords to generate one.';
    } else if (error.code === 'ESOCKET' || error.code === 'ECONNECTION') {
      errorMessage = 'Could not connect to Gmail SMTP server. Check your internet connection.';
    }
    
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}
